<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\..\Build\linq2db.Source.props" />

	<PropertyGroup>
		<AssemblyName>linq2db</AssemblyName>
		<RootNamespace>LinqToDB</RootNamespace>
		<DocumentationFile>bin\$(Configuration)\$(TargetFramework)\linq2db.xml</DocumentationFile>
		<LangVersion>14</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<!-- T4 support -->
		<Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
	</ItemGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Debug'">
		<DefineConstants>OVERRIDETOSTRING;$(DefineConstants)</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Include="SqlQuery\ReservedWords.txt" />
		<EmbeddedResource Include="SqlQuery\ReservedWordsOracle.txt" />
		<EmbeddedResource Include="SqlQuery\ReservedWordsFirebird.txt" />
		<EmbeddedResource Include="SqlQuery\ReservedWordsPostgres.txt" />
		<Compile Update="Common\Internal\MutableTuple.generated.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>MutableTuple.tt</DependentUpon>
		</Compile>

		<None Update="Common\Internal\MutableTuple.tt">
		  <Generator>TextTemplatingFileGenerator</Generator>
		  <LastGenOutput>MutableTuple.generated.cs</LastGenOutput>
		</None>

		<Compile Remove="Compatibility\**\*.cs" />

		<Compile Include="Compatibility\ComWrapper.cs" />
		<Compile Include="Compatibility\System\Threading\Tasks\TaskEx.cs" />
	</ItemGroup>

	<ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' OR '$(TargetFramework)' == 'netcoreapp2.1' OR '$(TargetFramework)' == 'netstandard2.1' OR '$(TargetFramework)' == 'netcoreapp3.1' OR '$(TargetFramework)' == 'net8.0' OR '$(TargetFramework)' == 'net10.0' ">
		<Compile Remove="Metadata\SystemDataLinqAttributeReader.cs" />
		<Compile Remove="Configuration\DataProviderElement.cs" />
		<Compile Remove="Configuration\DataProviderElementCollection.cs" />
		<Compile Remove="Configuration\ElementBase.cs" />
		<Compile Remove="Configuration\ElementCollectionBase.cs" />
		<Compile Remove="Configuration\LinqToDBSection.cs" />
		<Compile Remove="ServiceModel\**\*.cs;" />

		<Compile Include="Compatibility\System\Data\Linq\Binary.cs" />

		<PackageReference Include="System.ComponentModel.Annotations" Version="4.7.0" />
	</ItemGroup>

	<ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.1' OR '$(TargetFramework)' == 'netcoreapp3.1' OR '$(TargetFramework)' == 'netstandard2.0' OR '$(TargetFramework)' == 'netcoreapp2.1' OR '$(TargetFramework)' == 'net8.0' OR '$(TargetFramework)' == 'net10.0' ">
		<Compile Remove="Async\IAsyncEnumerable.cs" />
		<Compile Remove="Async\IAsyncEnumerator.cs" />
	  <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="1.1.1" />
	</ItemGroup>
</Project>
